#!/bin/sh
# @name SVEA TRX4 Gazebo Ackermann
# @type Rover
# @class Rover

# Keep airframe self-contained and explicit.
set VEHICLE_TYPE rover_ackermann
param set-default MAV_TYPE 10
param set-default CA_AIRFRAME 5
param set-default CA_R_REV 1

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=rover}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=rover_ackermann}

param set-default SIM_GZ_EN 1
param set-default SYS_HAS_BARO 0
param set-default EKF2_EN 0

param set-default NAV_ACC_RAD 0.5
param set-default COM_ARM_SDCARD 0

# Ackermann Parameters
param set-default RA_WHEEL_BASE 0.312
param set-default RA_ACC_RAD_GAIN 2
param set-default RA_ACC_RAD_MAX 3
param set-default RA_MAX_STR_ANG 0.5236
param set-default RA_STR_RATE_LIM 270

# Rate Control Parameters
param set-default RO_YAW_RATE_I 0.1
param set-default RO_YAW_RATE_P 0.1
param set-default RO_YAW_RATE_LIM 120
param set-default RO_YAW_ACCEL_LIM 800
param set-default RO_YAW_DECEL_LIM 800
param set-default RO_YAW_RATE_CORR 1
param set-default RO_YAW_EXPO 0.85
param set-default RO_YAW_SUPEXPO 0.3

# Attitude Control Parameters
param set-default RO_YAW_P 2.5

# Velocity Control Parameters
param set-default RO_ACCEL_LIM 1.5
param set-default RO_DECEL_LIM 10
param set-default RO_JERK_LIM 20
param set-default RO_MAX_THR_SPEED 2.8
param set-default RO_SPEED_LIM 2.5
param set-default RO_SPEED_I 0.01
param set-default RO_SPEED_P 0.1
param set-default RO_SPEED_RED 1

# Pure Pursuit parameters
param set-default PP_LOOKAHD_GAIN 1
param set-default PP_LOOKAHD_MAX 10
param set-default PP_LOOKAHD_MIN 1.5

# Wheels
param set-default SIM_GZ_WH_FUNC1 101
param set-default SIM_GZ_WH_MIN1 70
param set-default SIM_GZ_WH_MAX1 130
param set-default SIM_GZ_WH_DIS1 100

# Steering
param set-default SIM_GZ_SV_MAXA1 30
param set-default SIM_GZ_SV_MINA1 -30
param set-default CA_SV_CS_COUNT 1
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_REV 1

# Mikroe Board Behavior Match
param set-default COM_RC_IN_MODE 6
param set-default RC_MAP_ROLL 1
param set-default RC_MAP_THROTTLE 2
param set-default RC_MAP_FLTMODE 5
param set-default RC_MAP_KILL_SW 5
param set-default RC_MAP_ARM_SW 7
param set-default COM_ARM_SWISBTN 1
param set-default COM_RC_LOSS_T 0.5
param set-default NAV_RCL_ACT 6

# Allow auto arming bypass for testing
param set-default COM_PREARM_MODE 0
param set-default COM_DISARM_PRFLT -1

# Ensure all mode slots are Manual for offboard control via MAVLink MANUAL_CONTROL
param set-default COM_FLTMODE1 0
param set-default COM_FLTMODE2 0
param set-default COM_FLTMODE3 0
param set-default COM_FLTMODE4 0
param set-default COM_FLTMODE5 0
param set-default COM_FLTMODE6 0

# SVEA SITL helper for RC fallback and frame bridge
svea_sitl start
